package gui;

import business.EmpresaBusiness;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

public class Empresa extends javax.swing.JFrame {

    EmpresaBusiness empresaBusiness = new EmpresaBusiness();
    
    public void llenarCampos(){
        domain.Empresa empresa = this.empresaBusiness.getBusiness();
        jtfName.setText(empresa.getNombre());
        jtaVision.setText(empresa.getVision());
        jtaMision.setText(empresa.getMision());
        jtaHistory.setText(empresa.getHistoria());
        jtfPhone1.setText(empresa.getTelefono1());
        jtfPhone2.setText(empresa.getTelefono2());
        jtfEmail.setText(empresa.getCorreo());
        jtaAddress.setText(empresa.getDireccion());
        jtfFacebook.setText(empresa.getFacebook());
        jtfInstagram.setText(empresa.getInstagram());
        jtfWhatsapp.setText(empresa.getWhatsapp());
        jtfLogo.setText(empresa.getUrlLogo());
    }
        
    public Empresa() {
        initComponents();
        ImageIcon image = new ImageIcon(getClass().getResource("/images/logo.png"));
        Icon logo = new ImageIcon(image.getImage().getScaledInstance(jlLogo.getWidth(), jlLogo.getHeight(), Image.SCALE_DEFAULT));
        jlLogo.setIcon(logo);
        this.repaint();
        this.llenarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        jlLogo = new javax.swing.JLabel();
        jlUpdate = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaMision = new javax.swing.JTextArea();
        jlMision = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaVision = new javax.swing.JTextArea();
        jlVision = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtaHistory = new javax.swing.JTextArea();
        jlHistory = new javax.swing.JLabel();
        jlEmail = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jlPhone1 = new javax.swing.JLabel();
        jlFacebook = new javax.swing.JLabel();
        jlInstagram = new javax.swing.JLabel();
        jlWhatsapp = new javax.swing.JLabel();
        jlLogo2 = new javax.swing.JLabel();
        jtfFacebook = new javax.swing.JTextField();
        jtfPhone2 = new javax.swing.JTextField();
        jtfPhone1 = new javax.swing.JTextField();
        jtfInstagram = new javax.swing.JTextField();
        jlAddress = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jlPhone2 = new javax.swing.JLabel();
        jtfWhatsapp = new javax.swing.JTextField();
        jlName = new javax.swing.JLabel();
        jtfName = new javax.swing.JTextField();
        jtfLogo = new javax.swing.JTextField();
        jlMessageSuccess = new javax.swing.JLabel();
        jlMessageError = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtaAddress = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Empresa");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.black);
        setResizable(false);

        Panel.setBackground(new java.awt.Color(244, 130, 50));

        jlUpdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlUpdate.setText("Actualizar información de la Empresa");

        jtaMision.setColumns(20);
        jtaMision.setRows(5);
        jScrollPane1.setViewportView(jtaMision);

        jlMision.setText("Misión:");

        jtaVision.setColumns(20);
        jtaVision.setRows(5);
        jScrollPane2.setViewportView(jtaVision);

        jlVision.setText("Visión:");

        jtaHistory.setColumns(20);
        jtaHistory.setRows(5);
        jScrollPane3.setViewportView(jtaHistory);

        jlHistory.setText("Historia:");

        jlEmail.setText("Correo:");

        jtfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEmailActionPerformed(evt);
            }
        });

        jlPhone1.setText("Teléfono 1:");

        jlFacebook.setText("Facebook:");

        jlInstagram.setText("Instagram:");

        jlWhatsapp.setText("Whatsapp:");

        jlLogo2.setText("URL Logo:");

        jtfFacebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfFacebookActionPerformed(evt);
            }
        });

        jtfPhone2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPhone2ActionPerformed(evt);
            }
        });

        jtfPhone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPhone1ActionPerformed(evt);
            }
        });

        jtfInstagram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfInstagramActionPerformed(evt);
            }
        });

        jlAddress.setText("Dirreción:");

        btnUpdate.setText("Actualizar");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnBack.setText("Volver");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jlPhone2.setText("Teléfono 2:");

        jtfWhatsapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfWhatsappActionPerformed(evt);
            }
        });

        jlName.setText("Nombre: ");

        jtfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNameActionPerformed(evt);
            }
        });

        jlMessageSuccess.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlMessageSuccess.setForeground(new java.awt.Color(51, 255, 0));

        jlMessageError.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlMessageError.setForeground(new java.awt.Color(255, 0, 0));

        jtaAddress.setColumns(20);
        jtaAddress.setRows(5);
        jScrollPane4.setViewportView(jtaAddress);

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addGap(506, 506, 506)
                                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jlAddress)
                                            .addComponent(jlHistory)
                                            .addComponent(jlMision)))
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlPhone1)
                                            .addComponent(jlVision)
                                            .addComponent(jlPhone2)
                                            .addComponent(jlName)
                                            .addComponent(jlFacebook)
                                            .addComponent(jlInstagram)
                                            .addComponent(jlWhatsapp))
                                        .addGap(50, 50, 50)
                                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jtfPhone1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                                                .addComponent(jtfPhone2, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                                                .addComponent(jtfName)
                                                .addComponent(jtfFacebook)
                                                .addComponent(jtfWhatsapp, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                                                .addComponent(jtfInstagram))
                                            .addComponent(jlMessageSuccess)
                                            .addComponent(jlMessageError, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addGap(521, 521, 521)
                                        .addComponent(jlEmail))))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGap(268, 268, 268)
                                .addComponent(btnUpdate))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jlLogo2)))
                        .addGap(18, 18, 18)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(btnBack))
                            .addComponent(jtfLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(264, 264, 264)
                        .addComponent(jlUpdate)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlVision))
                        .addGap(41, 41, 41)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlPhone1)
                            .addComponent(jtfPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlMision))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlHistory)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(54, 54, 54)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfPhone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlPhone2)
                        .addComponent(jlAddress))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlFacebook)
                    .addComponent(jtfFacebook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEmail)
                    .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfInstagram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlInstagram))
                .addGap(40, 40, 40)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlLogo2)
                    .addComponent(jtfLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlWhatsapp)
                    .addComponent(jtfWhatsapp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jlMessageSuccess)
                .addGap(36, 36, 36)
                .addComponent(jlMessageError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnBack))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEmailActionPerformed

    private void jtfFacebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfFacebookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfFacebookActionPerformed

    private void jtfPhone2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPhone2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPhone2ActionPerformed

    private void jtfPhone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPhone1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPhone1ActionPerformed

    private void jtfInstagramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfInstagramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfInstagramActionPerformed

    private void jtfWhatsappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfWhatsappActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfWhatsappActionPerformed

    private void jtfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);
        Principal main = new Principal();
        main.setLocationRelativeTo(null);
        main.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String nombre = jtfName.getText();
        String vision = jtaVision.getText();
        String mision = jtaMision.getText();
        String historia = jtaHistory.getText();
        String telefono1 = jtfPhone1.getText();
        String telefono2 = jtfPhone2.getText();
        String correo = jtfEmail.getText();
        String direccion = jtaAddress.getText();
        String facebook = jtfFacebook.getText();
        String instagram = jtfInstagram.getText();
        String whatsapp = jtfWhatsapp.getText();
        String logo = jtfLogo.getText();
        
        domain.Empresa empresa = new domain.Empresa();
        
        if (nombre.equals("") || vision.equals("") || mision.equals("") || historia.equals("") || telefono1.equals("") || telefono2.equals("") || correo.equals("") || direccion.equals("") || facebook.equals("") || instagram.equals("") || whatsapp.equals("") || logo.equals("")) {
            jlMessageError.setText("Llene todos los campos por favor.");
            jlMessageSuccess.setText(""); 
        }else{
            empresa.setNombre(nombre);
            empresa.setVision(vision);
            empresa.setMision(mision);
            empresa.setHistoria(historia);
            empresa.setTelefono1(telefono1);
            empresa.setTelefono2(telefono2);
            empresa.setCorreo(correo);
            empresa.setDireccion(direccion);
            empresa.setFacebook(facebook);
            empresa.setInstagram(instagram);
            empresa.setWhatsapp(whatsapp);
            empresa.setUrlLogo(logo);
            
            if (this.empresaBusiness.updateBusiness(empresa) == 1) {
                jlMessageSuccess.setText("Se actualizó correctamente la información de la empresa.");  
                jlMessageError.setText("");
            }else{
                jlMessageError.setText("Hubo un problema al actualizar la información, intenta de nuevo.");
                jlMessageSuccess.setText(""); 
            }
            
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel jlAddress;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlFacebook;
    private javax.swing.JLabel jlHistory;
    private javax.swing.JLabel jlInstagram;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JLabel jlLogo2;
    private javax.swing.JLabel jlMessageError;
    private javax.swing.JLabel jlMessageSuccess;
    private javax.swing.JLabel jlMision;
    private javax.swing.JLabel jlName;
    private javax.swing.JLabel jlPhone1;
    private javax.swing.JLabel jlPhone2;
    private javax.swing.JLabel jlUpdate;
    private javax.swing.JLabel jlVision;
    private javax.swing.JLabel jlWhatsapp;
    private javax.swing.JTextArea jtaAddress;
    private javax.swing.JTextArea jtaHistory;
    private javax.swing.JTextArea jtaMision;
    private javax.swing.JTextArea jtaVision;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfFacebook;
    private javax.swing.JTextField jtfInstagram;
    private javax.swing.JTextField jtfLogo;
    private javax.swing.JTextField jtfName;
    private javax.swing.JTextField jtfPhone1;
    private javax.swing.JTextField jtfPhone2;
    private javax.swing.JTextField jtfWhatsapp;
    // End of variables declaration//GEN-END:variables
}
